export const CATALOGO_OBJETOS_PERDIDOS_AR = Object.freeze([
  {
    id: 'pelota-azul',
    nombre: 'pelota azul',
    etiqueta: 'Pelota',
    color: 'azul',
    categoria: 'juguetes',
    uso: 'jugar',
    forma: 'redonda',
    material: 'objetoPelotaAzul',
    tipo3d: 'esfera',
    dificultad: 1,
  },
  {
    id: 'manzana-roja',
    nombre: 'manzana roja',
    etiqueta: 'Manzana',
    color: 'rojo',
    categoria: 'frutas',
    uso: 'comer',
    forma: 'redonda',
    material: 'objetoManzanaRoja',
    tipo3d: 'esfera',
    dificultad: 1,
  },
  {
    id: 'libro-verde',
    nombre: 'libro verde',
    etiqueta: 'Libro',
    color: 'verde',
    categoria: 'utiles',
    uso: 'leer',
    forma: 'rectangular',
    material: 'objetoLibroVerde',
    tipo3d: 'caja-plana',
    dificultad: 1,
  },
  {
    id: 'cubo-morado',
    nombre: 'cubo morado',
    etiqueta: 'Cubo',
    color: 'morado',
    categoria: 'figuras',
    uso: 'construir',
    forma: 'cuadrada',
    material: 'objetoCuboMorado',
    tipo3d: 'caja',
    dificultad: 1,
  },
  {
    id: 'lapiz-naranja',
    nombre: 'lapiz naranja',
    etiqueta: 'Lapiz',
    color: 'naranja',
    categoria: 'utiles',
    uso: 'escribir',
    forma: 'alargada',
    material: 'objetoLapizNaranja',
    tipo3d: 'caja-larga',
    dificultad: 2,
  },
  {
    id: 'estrella-amarilla',
    nombre: 'estrella amarilla',
    etiqueta: 'Estrella',
    color: 'amarillo',
    categoria: 'figuras',
    uso: 'decorar',
    forma: 'estrella',
    material: 'objetoEstrellaAmarilla',
    tipo3d: 'placa',
    dificultad: 2,
  },
  {
    id: 'carro-rojo',
    nombre: 'carro rojo',
    etiqueta: 'Carro',
    color: 'rojo',
    categoria: 'juguetes',
    uso: 'transportar',
    forma: 'rectangular',
    material: 'objetoCarroRojo',
    tipo3d: 'caja',
    dificultad: 3,
  },
  {
    id: 'llave-dorada',
    nombre: 'llave dorada',
    etiqueta: 'Llave',
    color: 'dorado',
    categoria: 'herramientas',
    uso: 'abrir',
    forma: 'alargada',
    material: 'objetoLlaveDorada',
    tipo3d: 'caja-larga',
    dificultad: 3,
  },
  {
    id: 'gafas-azules',
    nombre: 'gafas azules',
    etiqueta: 'Gafas',
    color: 'azul',
    categoria: 'accesorios',
    uso: 'ver',
    forma: 'doble-circulo',
    material: 'objetoGafasAzules',
    tipo3d: 'doble-caja',
    dificultad: 4,
  },
  {
    id: 'corazon-rosado',
    nombre: 'corazon rosado',
    etiqueta: 'Corazon',
    color: 'rosado',
    categoria: 'figuras',
    uso: 'decorar',
    forma: 'corazon',
    material: 'objetoCorazonRosado',
    tipo3d: 'placa',
    dificultad: 4,
  },
]);

export const obtenerObjetosDisponiblesPorDificultad = (dificultad = 1) =>
  CATALOGO_OBJETOS_PERDIDOS_AR.filter((objeto) => objeto.dificultad <= dificultad);
