export const CATALOGO_OBJETOS_PERDIDOS_AR = Object.freeze([
  {
    id: 'manzana-roja',
    nombre: 'manzana roja',
    etiqueta: 'Manzana',
    color: 'rojo',
    categoria: 'frutas',
    uso: 'comer',
    forma: 'redonda',
    material: 'objetoManzanaRoja',
    tipo3d: 'manzana',
    escalaFigura: 0.82,
    etiquetaOffsetY: 0.24,
    dificultad: 1,
  },
  {
    id: 'bloque-juguete',
    nombre: 'bloque de juguete',
    etiqueta: 'Bloque',
    color: 'amarillo',
    categoria: 'juguetes',
    uso: 'construir',
    forma: 'cuadrada',
    material: 'objetoBloqueAmarillo',
    tipo3d: 'caja',
    escalaFigura: 0.82,
    etiquetaOffsetY: 0.22,
    dificultad: 1,
  },
  {
    id: 'oso-juguete',
    nombre: 'oso de juguete',
    etiqueta: 'Oso',
    color: 'cafe',
    categoria: 'juguetes',
    uso: 'abrazar',
    forma: 'redonda',
    material: 'objetoOsoCafe',
    tipo3d: 'oso-simple',
    escalaFigura: 0.76,
    etiquetaOffsetY: 0.26,
    dificultad: 1,
  },
  {
    id: 'libros-apilados',
    nombre: 'libros apilados',
    etiqueta: 'Libro',
    color: 'azul',
    categoria: 'utiles',
    uso: 'leer',
    forma: 'rectangular',
    material: 'objetoLibroAzul',
    tipo3d: 'libro',
    escalaFigura: 0.82,
    etiquetaOffsetY: 0.2,
    dificultad: 2,
  },
  {
    id: 'lapiz-naranja',
    nombre: 'lapiz',
    etiqueta: 'Lapiz',
    color: 'naranja',
    categoria: 'utiles',
    uso: 'escribir',
    forma: 'alargada',
    material: 'objetoLapizNaranja',
    tipo3d: 'lapiz',
    escalaFigura: 0.78,
    etiquetaOffsetY: 0.18,
    dificultad: 3,
  },
  {
    id: 'globo-terraqueo',
    nombre: 'globo terraqueo',
    etiqueta: 'Globo',
    color: 'azul',
    categoria: 'aula',
    uso: 'aprender geografia',
    forma: 'redonda',
    material: 'objetoGloboAzul',
    tipo3d: 'globo',
    escalaFigura: 0.82,
    etiquetaOffsetY: 0.26,
    dificultad: 4,
  },
]);

export const obtenerObjetosDisponiblesPorDificultad = (dificultad = 1) =>
  CATALOGO_OBJETOS_PERDIDOS_AR.filter((objeto) => objeto.dificultad <= dificultad);
