export const CATALOGO_OBJETOS_PERDIDOS_AR = Object.freeze([
  {
    id: 'circulo-azul',
    nombre: 'circulo azul',
    etiqueta: 'Circulo',
    color: 'azul',
    categoria: 'figuras',
    uso: 'reconocer circulos',
    forma: 'circulo',
    material: 'objetoFiguraAzul',
    tipo3d: 'esfera',
    dificultad: 1,
  },
  {
    id: 'cuadrado-rojo',
    nombre: 'cuadrado rojo',
    etiqueta: 'Cuadrado',
    color: 'rojo',
    categoria: 'figuras',
    uso: 'reconocer cuadrados',
    forma: 'cuadrado',
    material: 'objetoFiguraRoja',
    tipo3d: 'caja',
    dificultad: 1,
  },
  {
    id: 'rectangulo-verde',
    nombre: 'rectangulo verde',
    etiqueta: 'Rectangulo',
    color: 'verde',
    categoria: 'figuras',
    uso: 'reconocer rectangulos',
    forma: 'rectangulo',
    material: 'objetoFiguraVerde',
    tipo3d: 'caja-plana',
    dificultad: 1,
  },
  {
    id: 'cubo-morado',
    nombre: 'cubo morado',
    etiqueta: 'Cubo',
    color: 'morado',
    categoria: 'figuras',
    uso: 'comparar volumenes',
    forma: 'cubo',
    material: 'objetoFiguraMorada',
    tipo3d: 'caja',
    dificultad: 2,
  },
  {
    id: 'rectangulo-naranja',
    nombre: 'rectangulo naranja',
    etiqueta: 'Rectangulo',
    color: 'naranja',
    categoria: 'figuras',
    uso: 'comparar figuras alargadas',
    forma: 'rectangulo',
    material: 'objetoFiguraNaranja',
    tipo3d: 'caja-larga',
    dificultad: 2,
  },
  {
    id: 'circulo-amarillo',
    nombre: 'circulo amarillo',
    etiqueta: 'Circulo',
    color: 'amarillo',
    categoria: 'figuras',
    uso: 'distinguir color y forma',
    forma: 'circulo',
    material: 'objetoFiguraAmarilla',
    tipo3d: 'esfera',
    dificultad: 2,
  },
  {
    id: 'cuadrado-azul',
    nombre: 'cuadrado azul',
    etiqueta: 'Cuadrado',
    color: 'azul',
    categoria: 'figuras',
    uso: 'distinguir color y forma',
    forma: 'cuadrado',
    material: 'objetoFiguraAzul',
    tipo3d: 'caja',
    dificultad: 3,
  },
  {
    id: 'rectangulo-rojo',
    nombre: 'rectangulo rojo',
    etiqueta: 'Rectangulo',
    color: 'rojo',
    categoria: 'figuras',
    uso: 'distinguir color y forma',
    forma: 'rectangulo',
    material: 'objetoFiguraRoja',
    tipo3d: 'caja-plana',
    dificultad: 3,
  },
  {
    id: 'cubo-verde',
    nombre: 'cubo verde',
    etiqueta: 'Cubo',
    color: 'verde',
    categoria: 'figuras',
    uso: 'distinguir cuerpos geometricos',
    forma: 'cubo',
    material: 'objetoFiguraVerde',
    tipo3d: 'caja',
    dificultad: 4,
  },
  {
    id: 'circulo-morado',
    nombre: 'circulo morado',
    etiqueta: 'Circulo',
    color: 'morado',
    categoria: 'figuras',
    uso: 'distinguir color y forma',
    forma: 'circulo',
    material: 'objetoFiguraMorada',
    tipo3d: 'esfera',
    dificultad: 4,
  },
  {
    id: 'rectangulo-amarillo',
    nombre: 'rectangulo amarillo',
    etiqueta: 'Rectangulo',
    color: 'amarillo',
    categoria: 'figuras',
    uso: 'comparar longitud y color',
    forma: 'rectangulo',
    material: 'objetoFiguraAmarilla',
    tipo3d: 'caja-larga',
    dificultad: 4,
  },
]);

export const obtenerObjetosDisponiblesPorDificultad = (dificultad = 1) =>
  CATALOGO_OBJETOS_PERDIDOS_AR.filter((objeto) => objeto.dificultad <= dificultad);
