import { fonts, radii, shadows, spacing } from '../../../../constants/theme';

export const mercadoTheme = Object.freeze({
  colors: Object.freeze({
    cieloTop: '#F5CC8C',
    cieloBottom: '#C77D43',
    panelCream: '#FFF6E6',
    panelCreamStrong: '#FFE8B8',
    panelCreamSoft: '#FFFBEF',
    parchment: '#FFF2D8',
    panelWarm: '#FFD68A',
    borderGold: '#B96B1E',
    borderDark: '#7C4516',
    ink: '#4A2504',
    inkSoft: '#7B542B',
    whiteSoft: '#FFFDF7',
    greenPrimary: '#8CD83A',
    greenPrimaryDark: '#3B8E18',
    greenPrimaryBorder: '#5EAE23',
    blueAction: '#49B5FF',
    blueActionDark: '#1C71BF',
    redAction: '#FF745C',
    redActionDark: '#C94D36',
    brownAction: '#B87942',
    brownActionDark: '#7A4720',
    coin: '#FFCC3F',
    coinDeep: '#E28A11',
    star: '#FFCC39',
    starBorder: '#D17812',
    wood: '#A86026',
    woodDark: '#7D4218',
    woodLight: '#C9834A',
    shelf: '#B96A2B',
    shelfShadow: '#91501F',
    shadow: 'rgba(77, 34, 7, 0.22)',
    overlay: 'rgba(63, 33, 8, 0.52)',
    successMint: '#E9FFDB',
    successMintBorder: '#B8E46A',
    badgeBlue: '#8FDDF8',
    badgeBlueBorder: '#4696BA',
  }),
  fonts,
  radii,
  shadows,
  spacing,
});

export const mercadoCopy = Object.freeze({
  mascotaNombre: 'Guia del mercado',
  productoDockTitulo: 'Mochila',
  productoDockHint: 'Elige los productos correctos para completar la mision.',
  compraLabel: 'Comprar',
  pistaLabel: 'Pista',
  menuLabel: 'Menu',
});
